export const TRADE_STATUS_ORDER = [
  "DRAFT", "CONFIRMATION_PENDING", "CONFIRMED", "SELLER_CONTRACT_RECEIVED",
  "BUYER_PO_RECEIVED", "SHIPMENT_PLANNING", "BOOKED", "LOADED", "IN_TRANSIT",
  "ARRIVED", "DOCUMENTS_COMPLETED", "PAYMENT_COMPLETED", "BROKERAGE_COMPLETED",
  "TRADE_COMPLETED",
] as const;
export const TRADE_STATUS_SIDE_STATES = ["CANCELLED", "ON_HOLD", "DISPUTED"] as const;

Add trade status constants
