import { notFound } from "next/navigation";
import Image from "next/image";
import { prisma } from "@/lib/db";
import { requireSession } from "@/lib/margin";
import { PrintButton } from "@/components/PrintButton";

// This route renders a clean, letterhead-styled confirmation and relies on
// the browser's own "Print → Save as PDF" for the actual PDF file. That
// avoids depending on an unverified server-side PDF library in an
// environment where the build was never run end-to-end — it works
// immediately, in any browser, with zero extra dependencies. Swapping in a
// server-rendered PDF (e.g. @react-pdf/renderer or Puppeteer) is a
// reasonable later upgrade if pixel-perfect output becomes important.
export default async function TradeConfirmationPdfPage({ params }: { params: { id: string } }) {
  await requireSession();
  const c = await prisma.tradeConfirmation.findUnique({
    where: { id: params.id },
    include: { buyer: true, seller: true, product: true, qualitySpecs: { orderBy: { sortOrder: "asc" } } },
  });
  if (!c) notFound();

  return (
    <div className="max-w-3xl mx-auto">
      <div className="no-print mb-4 flex justify-end">
        <PrintButton />
      </div>

      <div className="bg-white border border-slate-200 print:border-0 p-10 text-sm text-slate-800">
        <div className="flex items-center justify-between border-b-2 pb-4 mb-6" style={{ borderColor: "#03224F" }}>
          <div className="flex items-center gap-3">
            <Image src="/logo.png" alt="logo" width={56} height={56} />
            <div>
              <p className="font-semibold text-base" style={{ color: "#03224F" }}>
                AL HAMZA MERIDIAN TRADING – FZCO
              </p>
              <p className="text-xs text-slate-500">Dubai, United Arab Emirates</p>
            </div>
          </div>
          <div className="text-right">
            <p className="text-xs text-slate-400">Trade Confirmation No.</p>
            <p className="font-semibold" style={{ color: "#03224F" }}>
              {c.status === "DRAFT" ? "DRAFT — not yet issued" : c.confirmationNo}
            </p>
            <p className="text-xs text-slate-400 mt-1">
              Date: {c.confirmationDate.toISOString().slice(0, 10)}
            </p>
          </div>
        </div>

        <Row label="Seller" value={`${c.seller.legalCompanyName}${c.seller.address ? ", " + c.seller.address : ""}`} />
        <Row label="Buyer" value={`${c.buyer.companyName}${c.buyer.address ? ", " + c.buyer.address : ""}`} />
        <Row label="Commodity" value={c.product.name} />

        {(c.qualitySpecs.length > 0 || c.qualityFreeText) && (
          <div className="py-2 border-b border-slate-100">
            <p className="text-xs text-slate-400 mb-1">Quality</p>
            {c.qualitySpecs.length > 0 && (
              <table className="w-full text-xs mb-2">
                <tbody>
                  {c.qualitySpecs.map((s) => (
                    <tr key={s.id}>
                      <td className="py-0.5 pr-4 text-slate-500">{s.parameter}</td>
                      <td className="py-0.5">
                        {s.minMax ? `${s.minMax} ` : ""}
                        {s.requirement} {s.unit ?? ""}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
            {c.qualityFreeText && <p className="text-sm">{c.qualityFreeText}</p>}
          </div>
        )}

        <Row label="Crop" value={c.crop} />
        <Row label="Origin" value={c.origin} />
        <Row label="Shipment" value={c.shipmentPeriod} />
        <Row label="Packing" value={c.packing} />
        <Row label="Destination" value={c.destination} />
        <Row label="Price" value={`${c.currency} ${c.price.toFixed(2)} ${c.priceBasis ?? ""}`} />
        <Row label="Quantity" value={`${c.quantity} ${c.quantityUnit}${c.quantityTolerance ? " — " + c.quantityTolerance : ""}`} />
        <Row label="Incoterm" value={c.incoterm} />
        {c.brokerName && <Row label="Brokerage" value={`${c.brokerName}${c.brokerageTerms ? " — " + c.brokerageTerms : ""}`} />}
        <Row label="Payment Terms" value={c.paymentTerms} />
        {c.documentsRequired && <Row label="Documents" value={c.documentsRequired} />}
        {c.arbitration && <Row label="Arbitration" value={c.arbitration} />}
        {c.remarks && <Row label="Remarks" value={c.remarks} />}
        {c.specialClauses && <Row label="Special Clauses" value={c.specialClauses} />}

        <p className="text-xs text-slate-400 mt-8">
          This document was generated by the AL HAMZA MERIDIAN Trade Management System and is
          confidential.
        </p>
      </div>
    </div>
  );
}

function Row({ label, value }: { label: string; value?: string | null }) {
  if (!value) return null;
  return (
    <div className="py-2 border-b border-slate-100 grid grid-cols-4 gap-4">
      <p className="text-xs text-slate-400 col-span-1">{label}</p>
      <p className="text-sm col-span-3 whitespace-pre-wrap">{value}</p>
    </div>
  );
}
